# Generated by Django 4.1.7 on 2023-04-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_carousel', models.CharField(max_length=30)),
                ('descripccion_carousel', models.CharField(max_length=50)),
                ('publicacion', models.CharField(max_length=15)),
                ('descripccion', models.CharField(max_length=120)),
            ],
        ),
    ]
