# Generated by Django 4.1.7 on 2023-04-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptMe', '0002_rename_descripccion_post_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripcion',
            new_name='caracteristicas',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='descripcion_carousel',
            new_name='caracteristicas_carousel',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publicacion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo_carousel',
            new_name='nombre_carousel',
        ),
    ]
