# Generated by Django 4.1.7 on 2023-04-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptMe', '0003_rename_descripcion_post_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caracteristicas',
            field=models.CharField(max_length=250),
        ),
    ]
